FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    ansible \
    sshpass \
    openssh-client \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install docker

WORKDIR /ansible

CMD ["bash"]
