FROM ubuntu:latest

# Install SSH and Python (needed for Ansible)
RUN apt-get update && apt-get install -y openssh-server python3 sudo \
    && mkdir /var/run/sshd

# Create admin user
RUN useradd -rm -d /home/admin -s /bin/bash -g root -G sudo -u 1000 admin \
    && echo 'admin:admin' | chpasswd

# Allow SSH access
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
