FROM ubuntu:latest

RUN apt-get update && apt-get install -y openssh-server python3 python3-apt sudo \
    && mkdir /var/run/sshd

RUN useradd -rm -d /home/admin -s /bin/bash -g root -G sudo -u 1001 admin \
    && echo 'admin:admin' | chpasswd

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
